/**
 * Contract test against a REAL analyzer payload — not a hand-typed object
 * literal like every other test in this directory.
 *
 * THE GAP THIS CLOSES: apps/web depends only on @file-audit/shared for
 * types (`grep -rl "@file-audit/analyzer" apps/web` returns nothing) and
 * every one of its component tests mounts against object literals the
 * test author typed by hand. Meanwhile apps/api/src/__tests__/integration.test.ts
 * is the only suite that runs the REAL pipeline (qpdf -> pdf.js -> scorer),
 * but it only spot-asserts a handful of numbers and never serializes its
 * output anywhere the web suite can see. So if the analyzer renamed a
 * field, changed a severity string's casing, or restructured
 * `scoreProfiles`, api's suite would catch it and *every* web test would
 * stay green while the real UI broke. This file pins the actual shape a
 * real run produces and renders it through the real Vue tree.
 *
 * FIXTURE PROVENANCE — apps/web/app/__tests__/fixtures/analyzer-output.pdf.json
 *   Real, unedited output of `analyzeDocument()` (packages/analyzer/src/analyzer.ts,
 *   published as @file-audit/analyzer) run over
 *   controls/"COVID arrests PDF to post on web-210305T17262965.pdf" (an 18-page
 *   real-world ICJIA publication — chosen because it grades D with a mix of
 *   severities, including 2 Criticals, exercising more UI branches than a
 *   clean A-grade file would). Captured at v1.56.0 (2026-08-07) with qpdf
 *   12.3.2 on PATH and WCAG_VERSION unset (engine default: WCAG 2.2 AA).
 *   veraPDF was not run, so `pdfUaVerdict` is absent from the payload — the
 *   same shape a real deployment without veraPDF configured produces (see
 *   the `pdfUaVerdict` doc-comment in packages/shared/src/types.ts).
 *   Size ~105KB, under the ~150KB guideline, so nothing was trimmed.
 *   No field has been hand-edited after capture — fidelity to real output
 *   is the entire point of this fixture; if it ever needs to change,
 *   regenerate it, don't touch the JSON directly.
 *
 *   TO REGENERATE: write a throwaway tsx script (delete it when done —
 *   nothing like it should be committed) that does:
 *
 *     import { readFileSync, writeFileSync } from "node:fs";
 *     import { analyzeDocument } from "@file-audit/analyzer";
 *
 *     const buf = readFileSync(
 *       "<repo>/controls/COVID arrests PDF to post on web-210305T17262965.pdf",
 *     );
 *     const result = await analyzeDocument(
 *       buf,
 *       "COVID arrests PDF to post on web-210305T17262965.pdf",
 *     );
 *     writeFileSync(
 *       "<repo>/apps/web/app/__tests__/fixtures/analyzer-output.pdf.json",
 *       JSON.stringify(result, null, 2) + "\n",
 *     );
 *
 *   then run it with `pnpm --filter api exec tsx <script>` (qpdf must be on
 *   PATH; do NOT start `pnpm dev` for this). Re-check for absolute
 *   filesystem paths in the output before committing — there shouldn't be
 *   any, since `filename` is whatever string is passed as the second
 *   argument, not the disk path.
 */
import "./test-helpers";
import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, it, expect } from "vitest";
import { mount } from "@vue/test-utils";
import { SEVERITY_THRESHOLDS } from "@file-audit/shared";
import ReportVisualView from "../components/ReportVisualView.vue";
import ReportGradeHero from "../components/ReportGradeHero.vue";

// Loaded via fs.readFileSync + JSON.parse (matching the fixture-loading
// convention in apps/api/src/__tests__/integration.test.ts's `loadFixture`)
// rather than a static `import … from "*.json"` — a static import only
// typechecks because apps/web/.nuxt/tsconfig*.json (generated by `nuxt
// prepare`, not present in a fresh checkout) sets resolveJsonModule; reading
// it as a plain string sidesteps that generated-file dependency entirely.
const fixturePath = path.join(import.meta.dirname, "fixtures", "analyzer-output.pdf.json");
// `any` is intentional (and off repo-wide, see eslint.config.mjs): this is
// the raw captured payload, and its shape is exactly what this file asserts.
const fixture: any = JSON.parse(readFileSync(fixturePath, "utf8"));

// The exact severity taxonomy a category's `severity` field may take —
// derived from SEVERITY_THRESHOLDS (packages/shared/src/scoring.ts), the
// single source of truth both the scorer (getSeverity/severityForScore) and
// the UI's color map (SEVERITY_COLORS, same file) key off. `null` is the
// valid 4th state for a not-applicable/not-assessed category (score: null).
const KNOWN_SEVERITIES: ReadonlyArray<string> = SEVERITY_THRESHOLDS.map((t) => t.severity);

describe("analyzer output contract (real captured payload)", () => {
  // Guards the fixture itself against silent hand-editing — the header
  // comment above documents these exact facts about THIS capture. If a
  // regeneration ever changes them, update the header comment too.
  it("fixture sanity: matches its own documented provenance", () => {
    expect(fixture.filename).toBe("COVID arrests PDF to post on web-210305T17262965.pdf");
    expect(fixture.fileType).toBe("pdf");
    expect(fixture.pageCount).toBe(18);
    expect(fixture.grade).toBe("D");
    expect(
      fixture.categories.filter((c: { severity: string }) => c.severity === "Critical"),
    ).toHaveLength(2);
  });

  // ReportGradeHero.vue (grade/overallScore props, `gradeColor(props.grade)`,
  // template `{{ overallScore }}/100`); CLI's printResult (apps/cli/src/commands/audit.ts)
  // reads the identical two fields directly off the top-level result.
  it("has a top-level overallScore: number and grade: string", () => {
    expect(typeof fixture.overallScore).toBe("number");
    expect(typeof fixture.grade).toBe("string");
  });

  // fileType drives ActionPlan's per-format fix-copy selection
  // (~/utils/actionPlan.ts normalizeFileType/buildActionPlan) and
  // TechnicalReport.vue's `sourceApp` computed (Word/PowerPoint/Excel vs PDF
  // caption) and MethodologyCard's `file-type` prop.
  it("has a top-level fileType in the shared FileType union", () => {
    expect(["pdf", "docx", "pptx", "xlsx"]).toContain(fixture.fileType);
  });

  // ReportVisualView.vue's displayedGrade/displayedScore computeds and
  // ScoreCard.vue's displayedProfile computed (apps/web/app/components/ScoreCard.vue
  // lines ~306-310) BOTH independently prefer `scoreProfiles.strict.{grade,overallScore}`
  // over the top-level fields — the Visual and Detailed views would silently
  // disagree for any report where this profile is missing or malshaped.
  it("has scoreProfiles.strict with grade: string and overallScore: number", () => {
    expect(fixture.scoreProfiles).toBeTruthy();
    const strict = fixture.scoreProfiles.strict;
    expect(strict).toBeTruthy();
    expect(typeof strict.grade).toBe("string");
    expect(typeof strict.overallScore).toBe("number");
  });

  describe("categories[]", () => {
    it("is a non-empty array", () => {
      expect(Array.isArray(fixture.categories)).toBe(true);
      expect(fixture.categories.length).toBeGreaterThan(0);
    });

    // id: CategoryBars.vue (:key="cat.id"), ActionPlan.vue/buildActionPlan
    // (categoryId, PLAN_COPY[id] lookup), TechnicalReport's evidence anchor
    // (`#cat-${categoryId}`, ActionPlan.vue's `detailAnchor`).
    // label: CategoryBars.vue renders `cat.label` directly; ActionPlan falls
    // back to it as a title when a category id isn't in PLAN_COPY.
    // score: CategoryBars.vue's `scored`/`na` split (`c.score !== null`) and
    // bar-fill width `${cat.score}%`.
    // grade: CategoryBars.vue's `barColor()` -> `gradeColor(cat.grade)`
    // (@file-audit/shared).
    // severity: SeverityTiles.vue's tallySeverity, ActionPlan.vue's
    // `isPlanSeverity` gate (only "Critical"|"Moderate"|"Minor" become plan
    // steps), CategoryBars.vue's severity chip.
    // findings: ~/utils/findings.ts (firstActionableFinding/partitionCardFindings,
    // consumed by ActionPlan.vue) call `.startsWith` on every entry — a
    // non-string entry threw during render until the v1.56.0 fix (see
    // CHANGELOG "A forged shared report could permanently break its own
    // page"), which is exactly the class of bug a hand-typed `findings: [...]`
    // fixture can't catch because the author never types a non-string.
    it("every category has the fields the report views destructure, correctly typed", () => {
      expect(fixture.categories.length).toBeGreaterThan(0);
      for (const cat of fixture.categories) {
        expect(typeof cat.id).toBe("string");
        expect(cat.id.length).toBeGreaterThan(0);
        expect(typeof cat.label).toBe("string");
        expect(cat.label.length).toBeGreaterThan(0);

        expect(cat.score === null || typeof cat.score === "number").toBe(true);
        if (typeof cat.score === "number") {
          expect(cat.score).toBeGreaterThanOrEqual(0);
          expect(cat.score).toBeLessThanOrEqual(100);
        }

        expect(cat.grade === null || typeof cat.grade === "string").toBe(true);

        expect(cat.severity === null || KNOWN_SEVERITIES.includes(cat.severity)).toBe(true);

        expect(Array.isArray(cat.findings)).toBe(true);
        for (const finding of cat.findings) {
          expect(typeof finding).toBe("string");
        }
      }
    });

    // The fixture was deliberately chosen (see header) to carry at least one
    // Critical AND at least one "No issues found" category, so the taxonomy
    // check above isn't vacuously true over an all-clean or all-failing file.
    it("the fixture actually exercises more than one severity value", () => {
      const severities = new Set(fixture.categories.map((c: { severity: string }) => c.severity));
      expect(severities.has("Critical")).toBe(true);
      expect(severities.size).toBeGreaterThan(1);
    });
  });

  // VerdictStrip.vue reads conformance.status ("fail" branch also reads
  // .failures.length; the else-if reads .notAssessed.length).
  // TechnicalReport.vue's conformance-detail panel reads .status, .headline,
  // and iterates .failures[] (f.sc/f.name/f.level/f.issue/f.url) and
  // .notAssessed[] (n.sc/n.name/n.url, via its `notAssessedList` computed).
  describe("conformance", () => {
    it("has the shape VerdictStrip and TechnicalReport read", () => {
      const c = fixture.conformance;
      expect(c).toBeTruthy();
      expect(["fail", "no-automated-failures", "incomplete"]).toContain(c.status);
      expect(typeof c.headline).toBe("string");

      expect(Array.isArray(c.failures)).toBe(true);
      for (const f of c.failures) {
        expect(typeof f.sc).toBe("string");
        expect(typeof f.name).toBe("string");
        expect(["A", "AA"]).toContain(f.level);
        expect(typeof f.category).toBe("string");
        expect(typeof f.issue).toBe("string");
        expect(typeof f.url).toBe("string");
      }

      expect(Array.isArray(c.notAssessed)).toBe(true);
      for (const n of c.notAssessed) {
        expect(typeof n.sc).toBe("string");
        expect(typeof n.name).toBe("string");
        expect(typeof n.url).toBe("string");
      }
    });
  });
});

describe("fixture flows through the real UI (ReportVisualView)", () => {
  // This is the piece a pure JSON-shape assertion above cannot provide: if a
  // component destructures a field this fixture doesn't actually have (or
  // the analyzer renamed one), mounting throws here even though every
  // assertion above could still be checking the wrong keys entirely.
  it("mounts without throwing", () => {
    expect(() => mount(ReportVisualView, { props: { result: fixture } })).not.toThrow();
  });

  it("renders the fixture's OWN grade and score (via ReportGradeHero), not a hardcoded value", () => {
    const w = mount(ReportVisualView, { props: { result: fixture } });
    const hero = w.findComponent(ReportGradeHero);
    expect(hero.exists()).toBe(true);
    // Same preference order as ReportVisualView's displayedGrade/displayedScore
    // computeds: scoreProfiles.strict wins over the top-level fields.
    expect(hero.props("grade")).toBe(fixture.scoreProfiles.strict.grade);
    expect(hero.props("overallScore")).toBe(fixture.scoreProfiles.strict.overallScore);
    expect(w.text()).toContain(`${fixture.scoreProfiles.strict.overallScore}`);
    expect(w.html()).toContain("/100");
  });

  it("renders the action plan, category bars, and technical report sections (hasCategories branch)", () => {
    const w = mount(ReportVisualView, { props: { result: fixture } });
    expect(w.text()).toContain("Your action plan");
    expect(w.find("[data-testid='bar-row']").exists()).toBe(true);
    expect(w.find("#technical-report").exists()).toBe(true);
    // 2 Criticals (per the fixture-sanity check above) means the plan is
    // non-empty and the pass card must NOT render.
    expect(w.find("[data-testid='plan-pass-card']").exists()).toBe(false);
  });
});
