import fileSaver from 'file-saver'
const { saveAs } = fileSaver
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  TableRow,
  TableCell,
  Table,
  WidthType,
  ExternalHyperlink,
} from 'docx'

interface HelpLink {
  label: string
  url: string
}

interface Category {
  id: string
  label: string
  score: number | null
  grade: string | null
  severity: string | null
  findings: string[]
  explanation?: string
  helpLinks?: HelpLink[]
}

interface ReportResult {
  filename: string
  pageCount: number
  overallScore: number
  grade: string
  isScanned: boolean
  executiveSummary: string
  categories: Category[]
  warnings?: string[]
}

function timestamp(): string {
  return new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZoneName: 'short',
  })
}

function baseFilename(result: ReportResult): string {
  const name = result.filename.replace(/\.pdf$/i, '')
  const date = new Date().toISOString().slice(0, 10)
  return `${name}-accessibility-report-${date}`
}

function gradeLabel(grade: string): string {
  const map: Record<string, string> = {
    A: 'Excellent',
    B: 'Good',
    C: 'Needs Improvement',
    D: 'Poor',
    F: 'Failing',
  }
  return map[grade] || grade
}

function severityEmoji(severity: string | null): string {
  if (!severity) return ''
  const map: Record<string, string> = {
    Pass: '✅',
    Minor: 'ℹ️',
    Moderate: '⚠️',
    Critical: '🔴',
  }
  return map[severity] || ''
}

// ── Markdown ──────────────────────────────────────────────────────────────

interface BrandingInfo {
  appName: string
  siteUrl: string
}

function buildMarkdown(result: ReportResult, branding: BrandingInfo): string {
  const lines: string[] = []

  lines.push(`# PDF Accessibility Report`)
  lines.push('')
  lines.push(`**File:** ${result.filename}`)
  lines.push(`**Pages:** ${result.pageCount}`)
  lines.push(`**Date:** ${timestamp()}`)
  lines.push(`**Overall Score:** ${result.overallScore}/100`)
  lines.push(`**Grade:** ${result.grade} — ${gradeLabel(result.grade)}`)
  if (result.isScanned) lines.push(`**Status:** ⚠️ Scanned document detected`)
  lines.push('')

  lines.push('---')
  lines.push('')
  lines.push('## Executive Summary')
  lines.push('')
  lines.push(result.executiveSummary)
  lines.push('')

  if (result.warnings?.length) {
    lines.push('> **Warnings:**')
    for (const w of result.warnings) {
      lines.push(`> - ${w}`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push('')
  lines.push('## Category Scores')
  lines.push('')
  lines.push('| Category | Score | Grade | Severity |')
  lines.push('|----------|-------|-------|----------|')
  for (const cat of result.categories) {
    const score = cat.score !== null ? `${cat.score}/100` : 'N/A'
    const grade = cat.grade || '—'
    const sev = cat.severity ? `${severityEmoji(cat.severity)} ${cat.severity}` : 'N/A'
    lines.push(`| ${cat.label} | ${score} | ${grade} | ${sev} |`)
  }
  lines.push('')

  lines.push('---')
  lines.push('')
  lines.push('## Detailed Findings')
  lines.push('')

  for (const cat of result.categories) {
    const scoreStr = cat.score !== null ? `${cat.score}/100 (${cat.grade})` : 'N/A'
    lines.push(`### ${cat.label} — ${scoreStr}`)
    lines.push('')

    if (cat.severity) {
      lines.push(`**Severity:** ${severityEmoji(cat.severity)} ${cat.severity}`)
      lines.push('')
    }

    if (cat.explanation) {
      lines.push(`> ${cat.explanation}`)
      lines.push('')
    }

    lines.push('**Findings:**')
    lines.push('')
    for (const f of cat.findings) {
      lines.push(`- ${f}`)
    }
    lines.push('')

    if (cat.helpLinks?.length) {
      lines.push('**Resources:**')
      lines.push('')
      for (const link of cat.helpLinks) {
        lines.push(`- [${link.label}](${link.url})`)
      }
      lines.push('')
    }
  }

  lines.push('---')
  lines.push('')
  lines.push(`*Report generated by [${branding.appName}](${branding.siteUrl}) — ${timestamp()}*`)

  return lines.join('\n')
}

// ── JSON ──────────────────────────────────────────────────────────────────

const WCAG_MAP: Record<string, { criteria: string[]; principle: string; remediation: string }> = {
  text_extractability: {
    criteria: ['1.3.1 Info and Relationships (Level A)', '1.4.5 Images of Text (Level AA)'],
    principle: 'Perceivable',
    remediation: 'Run OCR on scanned pages (Adobe Acrobat: Scan & OCR → Recognize Text), then add tags (Accessibility → Add Tags to Document). Verify the tag structure covers all content.',
  },
  title_language: {
    criteria: ['2.4.2 Page Titled (Level A)', '3.1.1 Language of Page (Level A)'],
    principle: 'Operable / Understandable',
    remediation: 'Set the document title in File → Properties → Description. Set the language in File → Properties → Advanced → Language dropdown.',
  },
  heading_structure: {
    criteria: ['1.3.1 Info and Relationships (Level A)', '2.4.6 Headings and Labels (Level AA)'],
    principle: 'Perceivable / Operable',
    remediation: 'Open the Tags panel, identify text that serves as section headings, and change their tag type to H1–H6 in a logical hierarchy. Do not skip levels (e.g., H1 → H3).',
  },
  alt_text: {
    criteria: ['1.1.1 Non-text Content (Level A)'],
    principle: 'Perceivable',
    remediation: 'In the Tags panel, find each <Figure> tag, right-click → Properties, and enter descriptive alt text. Mark decorative images as artifacts instead.',
  },
  bookmarks: {
    criteria: ['2.4.5 Multiple Ways (Level AA)'],
    principle: 'Operable',
    remediation: 'Open the Bookmarks panel. Create bookmarks for each major section, or auto-generate from heading tags (Options → New Bookmarks from Structure).',
  },
  table_markup: {
    criteria: ['1.3.1 Info and Relationships (Level A)'],
    principle: 'Perceivable',
    remediation: 'In the Tags panel, expand each <Table> tag. Change header cell tags from <TD> to <TH>. Add scope attributes (Row or Column) to header cells.',
  },
  link_quality: {
    criteria: ['2.4.4 Link Purpose in Context (Level A)'],
    principle: 'Operable',
    remediation: 'Replace raw URLs with descriptive link text in the source document before exporting to PDF. In Acrobat, edit link properties via Edit PDF.',
  },
  form_accessibility: {
    criteria: ['1.3.1 Info and Relationships (Level A)', '4.1.2 Name, Role, Value (Level A)'],
    principle: 'Perceivable / Robust',
    remediation: 'Right-click each form field → Properties → General tab → enter a descriptive Tooltip. The tooltip becomes the accessible label announced by screen readers.',
  },
  reading_order: {
    criteria: ['1.3.2 Meaningful Sequence (Level A)'],
    principle: 'Perceivable',
    remediation: 'Use the Reading Order tool (Accessibility → Reading Order) to verify and reorder elements so the tag sequence matches the intended reading flow.',
  },
}

function buildJSON(result: ReportResult, branding: BrandingInfo): string {
  const failingCategories = result.categories.filter(c => c.score !== null && c.score < 90)
  const passingCategories = result.categories.filter(c => c.score !== null && c.score >= 90)
  const naCategories = result.categories.filter(c => c.score === null)

  const report = {
    reportMeta: {
      generatedAt: new Date().toISOString(),
      generatedAtFormatted: timestamp(),
      tool: branding.appName,
      toolUrl: branding.siteUrl,
      schemaVersion: '2.0',
    },
    file: {
      name: result.filename,
      pages: result.pageCount,
      isScanned: result.isScanned,
    },
    score: {
      overall: result.overallScore,
      grade: result.grade,
      gradeLabel: gradeLabel(result.grade),
    },
    executiveSummary: result.executiveSummary,
    warnings: result.warnings || [],
    categories: result.categories.map(cat => {
      const wcag = WCAG_MAP[cat.id]
      return {
        id: cat.id,
        label: cat.label,
        score: cat.score,
        grade: cat.grade,
        severity: cat.severity,
        status: cat.score === null ? 'not-applicable' : cat.score >= 90 ? 'pass' : cat.score >= 70 ? 'minor' : cat.score >= 40 ? 'moderate' : 'fail',
        findings: cat.findings,
        explanation: cat.explanation || null,
        helpLinks: cat.helpLinks || [],
        wcag: wcag ? {
          successCriteria: wcag.criteria,
          principle: wcag.principle,
          remediation: wcag.remediation,
        } : null,
      }
    }),
    remediationPlan: {
      summary: failingCategories.length === 0
        ? 'No remediation needed — all scored categories pass.'
        : `${failingCategories.length} categor${failingCategories.length === 1 ? 'y needs' : 'ies need'} remediation.`,
      prioritizedSteps: failingCategories
        .sort((a, b) => (a.score ?? 100) - (b.score ?? 100))
        .map((cat, i) => ({
          priority: i + 1,
          category: cat.label,
          currentScore: cat.score,
          severity: cat.severity,
          wcagCriteria: WCAG_MAP[cat.id]?.criteria || [],
          action: WCAG_MAP[cat.id]?.remediation || 'Review findings and remediate in Adobe Acrobat.',
        })),
    },
    llmContext: {
      description: 'This section provides structured context for LLMs processing this accessibility report.',
      prompt: `You are reviewing a PDF accessibility audit for "${result.filename}" (${result.pageCount} pages). `
        + `It scored ${result.overallScore}/100 (Grade ${result.grade}). `
        + (failingCategories.length > 0
          ? `The following categories need remediation: ${failingCategories.map(c => `${c.label} (${c.score}/100)`).join(', ')}. `
          : 'All scored categories pass. ')
        + `Use the remediationPlan.prioritizedSteps array for ordered fix instructions. `
        + `Each category includes WCAG 2.1 success criteria references and tool-specific remediation steps for Adobe Acrobat.`,
      standards: ['WCAG 2.1 Level AA', 'ADA Title II (effective April 2026)', 'Section 508', 'PDF/UA (ISO 14289-1)'],
      scoringScale: {
        pass: '90–100',
        minor: '70–89',
        moderate: '40–69',
        fail: '0–39',
      },
    },
  }
  return JSON.stringify(report, null, 2)
}

// ── DOCX ──────────────────────────────────────────────────────────────────

function gradeColor(grade: string): string {
  const map: Record<string, string> = {
    A: '22c55e',
    B: '14b8a6',
    C: 'eab308',
    D: 'f97316',
    F: 'ef4444',
  }
  return map[grade] || '666666'
}

function severityColor(severity: string | null): string {
  const map: Record<string, string> = {
    Pass: '22c55e',
    Minor: '3b82f6',
    Moderate: 'eab308',
    Critical: 'ef4444',
  }
  return map[severity || ''] || '999999'
}

async function buildDocx(result: ReportResult, branding: BrandingInfo): Promise<Blob> {
  const children: Paragraph[] = []

  // Title
  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: 'PDF Accessibility Report', bold: true, size: 48, font: 'Calibri' }),
      ],
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
    })
  )

  // Metadata block
  const metaLines = [
    { label: 'File:', value: result.filename },
    { label: 'Pages:', value: String(result.pageCount) },
    { label: 'Date:', value: timestamp() },
    { label: 'Overall Score:', value: `${result.overallScore}/100` },
    { label: 'Grade:', value: `${result.grade} — ${gradeLabel(result.grade)}` },
  ]

  for (const m of metaLines) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: m.label, bold: true, size: 22, font: 'Calibri' }),
          new TextRun({ text: ' ' + m.value, size: 22, font: 'Calibri' }),
        ],
        spacing: { after: 60 },
      })
    )
  }

  if (result.isScanned) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: '⚠ This PDF appears to be a scanned image. OCR and full remediation are required.',
            bold: true,
            size: 22,
            font: 'Calibri',
            color: 'f97316',
          }),
        ],
        spacing: { before: 120, after: 120 },
      })
    )
  }

  // Divider
  children.push(
    new Paragraph({
      border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: 'cccccc' } },
      spacing: { before: 200, after: 200 },
    })
  )

  // Executive Summary
  children.push(
    new Paragraph({
      children: [new TextRun({ text: 'Executive Summary', bold: true, size: 28, font: 'Calibri' })],
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 120 },
    })
  )
  children.push(
    new Paragraph({
      children: [new TextRun({ text: result.executiveSummary, size: 22, font: 'Calibri' })],
      spacing: { after: 200 },
    })
  )

  // Warnings
  if (result.warnings?.length) {
    for (const w of result.warnings) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: `⚠ ${w}`, size: 20, font: 'Calibri', color: 'b45309', italics: true })],
          spacing: { after: 60 },
        })
      )
    }
    children.push(new Paragraph({ spacing: { after: 120 } }))
  }

  // Score summary table
  children.push(
    new Paragraph({
      children: [new TextRun({ text: 'Category Scores', bold: true, size: 28, font: 'Calibri' })],
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 120 },
    })
  )

  const headerRow = new TableRow({
    tableHeader: true,
    children: ['Category', 'Score', 'Grade', 'Severity'].map(
      text =>
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text, bold: true, size: 20, font: 'Calibri', color: 'ffffff' })] })],
          shading: { fill: '333333' },
          width: text === 'Category' ? { size: 40, type: WidthType.PERCENTAGE } : { size: 20, type: WidthType.PERCENTAGE },
        })
    ),
  })

  const dataRows = result.categories.map(
    cat =>
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: cat.label, size: 20, font: 'Calibri' })] })],
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: cat.score !== null ? `${cat.score}` : 'N/A', size: 20, font: 'Calibri' })],
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: cat.grade || '—',
                    bold: true,
                    size: 20,
                    font: 'Calibri',
                    color: cat.grade ? gradeColor(cat.grade) : '999999',
                  }),
                ],
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: cat.severity || 'N/A',
                    size: 20,
                    font: 'Calibri',
                    color: severityColor(cat.severity),
                  }),
                ],
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
        ],
      })
  )

  children.push(new Paragraph({ spacing: { after: 40 } }))

  const scoreTable = new Table({
    rows: [headerRow, ...dataRows],
    width: { size: 100, type: WidthType.PERCENTAGE },
  })

  // Divider before detailed findings
  const divider = new Paragraph({
    border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: 'cccccc' } },
    spacing: { before: 300, after: 200 },
  })

  // Detailed findings
  const detailParagraphs: Paragraph[] = []

  detailParagraphs.push(
    new Paragraph({
      children: [new TextRun({ text: 'Detailed Findings', bold: true, size: 28, font: 'Calibri' })],
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
    })
  )

  for (const cat of result.categories) {
    const scoreStr = cat.score !== null ? `${cat.score}/100 (${cat.grade})` : 'N/A'

    // Category heading
    detailParagraphs.push(
      new Paragraph({
        children: [
          new TextRun({ text: cat.label, bold: true, size: 24, font: 'Calibri' }),
          new TextRun({ text: ` — ${scoreStr}`, size: 24, font: 'Calibri', color: cat.grade ? gradeColor(cat.grade) : '999999' }),
        ],
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 240, after: 80 },
      })
    )

    // Severity badge
    if (cat.severity) {
      detailParagraphs.push(
        new Paragraph({
          children: [
            new TextRun({ text: 'Severity: ', bold: true, size: 20, font: 'Calibri' }),
            new TextRun({ text: cat.severity, bold: true, size: 20, font: 'Calibri', color: severityColor(cat.severity) }),
          ],
          spacing: { after: 80 },
        })
      )
    }

    // Explanation
    if (cat.explanation) {
      detailParagraphs.push(
        new Paragraph({
          children: [new TextRun({ text: cat.explanation, size: 20, font: 'Calibri', italics: true, color: '666666' })],
          spacing: { after: 120 },
          indent: { left: 360 },
        })
      )
    }

    // Findings
    for (const f of cat.findings) {
      const isFailure = cat.score !== null && (f.toLowerCase().includes('not found') || f.toLowerCase().includes('no ') || f.toLowerCase().includes('missing') || f.toLowerCase().includes('not tagged') || f.toLowerCase().includes('unlabeled'))
      const isSuccess = f.toLowerCase().includes('found') || f.toLowerCase().includes('present') || f.toLowerCase().includes('all ') || f.toLowerCase().includes('declared')
      const bullet = isFailure ? '✗' : isSuccess ? '✓' : '•'
      const color = isFailure ? 'ef4444' : isSuccess ? '22c55e' : '666666'

      detailParagraphs.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${bullet} `, bold: true, size: 20, font: 'Calibri', color }),
            new TextRun({ text: f, size: 20, font: 'Calibri' }),
          ],
          spacing: { after: 40 },
          indent: { left: 360 },
        })
      )
    }

    // Help links
    if (cat.helpLinks?.length) {
      detailParagraphs.push(
        new Paragraph({
          children: [new TextRun({ text: 'Resources:', bold: true, size: 20, font: 'Calibri', color: '3b82f6' })],
          spacing: { before: 80, after: 40 },
          indent: { left: 360 },
        })
      )
      for (const link of cat.helpLinks) {
        detailParagraphs.push(
          new Paragraph({
            children: [
              new TextRun({ text: '→ ', size: 20, font: 'Calibri', color: '3b82f6' }),
              new ExternalHyperlink({
                children: [new TextRun({ text: link.label, size: 20, font: 'Calibri', color: '3b82f6', underline: {} })],
                link: link.url,
              }),
            ],
            spacing: { after: 30 },
            indent: { left: 720 },
          })
        )
      }
    }
  }

  // Footer
  detailParagraphs.push(
    new Paragraph({
      border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: 'cccccc' } },
      spacing: { before: 300, after: 120 },
    })
  )
  detailParagraphs.push(
    new Paragraph({
      children: [
        new TextRun({ text: 'Report generated by ', size: 18, font: 'Calibri', italics: true, color: '999999' }),
        new ExternalHyperlink({
          children: [new TextRun({ text: branding.appName, size: 18, font: 'Calibri', italics: true, color: '3b82f6', underline: {} })],
          link: branding.siteUrl,
        }),
        new TextRun({ text: ` — ${timestamp()}`, size: 18, font: 'Calibri', italics: true, color: '999999' }),
      ],
      alignment: AlignmentType.CENTER,
    })
  )

  const doc = new Document({
    sections: [
      {
        children: [...children, scoreTable, divider, ...detailParagraphs],
      },
    ],
  })

  return await Packer.toBlob(doc)
}

// ── HTML ──────────────────────────────────────────────────────────────────

function escapeHtml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

function buildHtml(result: ReportResult, branding: BrandingInfo): string {
  const gc = (grade: string) => {
    const m: Record<string, string> = { A: '#22c55e', B: '#14b8a6', C: '#eab308', D: '#f97316', F: '#ef4444' }
    return m[grade] || '#666'
  }
  const sc = (sev: string | null) => {
    const m: Record<string, string> = { Pass: '#22c55e', Minor: '#3b82f6', Moderate: '#eab308', Critical: '#ef4444' }
    return m[sev || ''] || '#999'
  }

  const catRows = result.categories.map(cat => {
    const score = cat.score !== null ? `${cat.score}` : 'N/A'
    const grade = cat.grade || '—'
    const sev = cat.severity || 'N/A'
    return `<tr>
      <td style="padding:8px 12px;border-bottom:1px solid #222">${escapeHtml(cat.label)}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #222;text-align:center;font-family:monospace;color:${gc(cat.grade || '')}">${score}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #222;text-align:center;font-weight:bold;color:${gc(cat.grade || '')}">${grade}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #222;text-align:center"><span style="color:${sc(cat.severity)};background:${sc(cat.severity)}15;padding:2px 8px;border-radius:12px;font-size:12px">${escapeHtml(sev)}</span></td>
    </tr>`
  }).join('\n')

  const detailSections = result.categories.map(cat => {
    const scoreStr = cat.score !== null ? `${cat.score}/100 (${cat.grade})` : 'N/A'

    const findingsHtml = cat.findings.map(f => {
      const isFail = cat.score !== null && (f.toLowerCase().includes('not found') || f.toLowerCase().includes('no ') || f.toLowerCase().includes('missing') || f.toLowerCase().includes('not tagged') || f.toLowerCase().includes('unlabeled'))
      const isOk = f.toLowerCase().includes('found') || f.toLowerCase().includes('present') || f.toLowerCase().includes('all ') || f.toLowerCase().includes('declared')
      const icon = isFail ? '✗' : isOk ? '✓' : cat.score === null ? '–' : '•'
      const color = isFail ? '#ef4444' : isOk ? '#22c55e' : cat.score === null ? '#eab308' : '#999'
      return `<div style="display:flex;gap:8px;margin-bottom:4px;font-size:14px;color:#ccc">
        <span style="color:${color};font-weight:bold;flex-shrink:0">${icon}</span>
        <span>${escapeHtml(f)}</span>
      </div>`
    }).join('\n')

    const linksHtml = (cat.helpLinks?.length)
      ? `<div style="margin-top:12px;padding-top:10px;border-top:1px solid #1a1a1a">
          <div style="font-size:11px;color:#888;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:8px">Learn more</div>
          <div style="display:flex;flex-wrap:wrap;gap:6px">
            ${cat.helpLinks.map(l => `<a href="${escapeHtml(l.url)}" target="_blank" rel="noopener noreferrer" style="font-size:12px;color:#60a5fa;background:#3b82f610;padding:4px 10px;border-radius:6px;text-decoration:none">${escapeHtml(l.label)} ↗</a>`).join('\n')}
          </div>
        </div>`
      : ''

    const explanationHtml = cat.explanation
      ? `<div style="margin-bottom:12px;font-size:13px;color:#888;background:#0d0d0d;border:1px solid #1a1a1a;border-radius:8px;padding:10px 14px">
          <strong style="color:#aaa">What this checks:</strong> ${escapeHtml(cat.explanation)}
        </div>`
      : ''

    const sevBadge = cat.severity
      ? `<span style="color:${sc(cat.severity)};background:${sc(cat.severity)}15;padding:2px 10px;border-radius:12px;font-size:12px;margin-left:auto">${escapeHtml(cat.severity)}</span>`
      : ''

    return `<div style="background:#111;border:1px solid #222;border-radius:12px;padding:20px;margin-bottom:12px">
      <div style="display:flex;align-items:center;gap:10px;margin-bottom:12px">
        <h3 style="margin:0;font-size:16px;color:#fff">${escapeHtml(cat.label)}</h3>
        <span style="font-family:monospace;font-size:14px;color:${gc(cat.grade || '')}">${scoreStr}</span>
        ${sevBadge}
      </div>
      ${explanationHtml}
      ${findingsHtml}
      ${linksHtml}
    </div>`
  }).join('\n')

  const warningsHtml = result.warnings?.length
    ? `<div style="background:#854d0e15;border:1px solid #854d0e30;border-radius:12px;padding:14px;margin-bottom:20px">
        ${result.warnings.map(w => `<p style="color:#fbbf24;font-size:14px;margin:0">${escapeHtml(w)}</p>`).join('\n')}
      </div>`
    : ''

  const scannedHtml = result.isScanned
    ? `<div style="background:#f9731615;border:1px solid #f9731630;border-radius:12px;padding:14px;margin-bottom:20px">
        <p style="color:#fdba74;font-size:14px;font-weight:500;margin:0">This PDF appears to be a scanned image. Screen readers cannot access its content. OCR and full remediation are required.</p>
      </div>`
    : ''

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Accessibility Report — ${escapeHtml(result.filename)}</title>
<style>
  body { background:#0a0a0a; color:#f5f5f5; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; margin:0; padding:40px 20px; line-height:1.5 }
  .container { max-width:800px; margin:0 auto }
  a { color:#60a5fa }
  @media print { body { background:#fff; color:#000 } .container { max-width:100% } }
</style>
</head>
<body>
<div class="container">

  <h1 style="text-align:center;font-size:24px;margin-bottom:4px">PDF Accessibility Report</h1>
  <p style="text-align:center;font-size:13px;color:#888;margin-top:0">${timestamp()}</p>

  <div style="text-align:center;margin:30px 0">
    <p style="font-size:14px;color:#aaa;margin-bottom:12px">${escapeHtml(result.filename)} — ${result.pageCount} page${result.pageCount !== 1 ? 's' : ''}</p>
    <div style="width:120px;height:120px;border-radius:50%;border:4px solid ${gc(result.grade)};background:${gc(result.grade)}15;display:inline-flex;align-items:center;justify-content:center">
      <span style="font-size:56px;font-weight:900;color:${gc(result.grade)}">${result.grade}</span>
    </div>
    <p style="font-size:24px;font-weight:bold;margin:12px 0 4px">${result.overallScore}<span style="font-size:16px;color:#888">/100</span></p>
    <p style="font-size:14px;color:${gc(result.grade)};font-weight:500;margin:0">${gradeLabel(result.grade)}</p>
  </div>

  ${scannedHtml}
  ${warningsHtml}

  <div style="background:#111;border:1px solid #222;border-radius:12px;padding:16px 20px;margin-bottom:24px">
    <h2 style="font-size:14px;color:#aaa;margin:0 0 8px;text-transform:uppercase;letter-spacing:0.05em">Executive Summary</h2>
    <p style="font-size:14px;color:#ccc;margin:0">${escapeHtml(result.executiveSummary)}</p>
  </div>

  <h2 style="font-size:18px;margin-bottom:12px">Category Scores</h2>
  <table style="width:100%;border-collapse:collapse;background:#111;border:1px solid #222;border-radius:12px;overflow:hidden;margin-bottom:30px">
    <thead>
      <tr style="background:#222">
        <th style="padding:8px 12px;text-align:left;font-size:12px;color:#aaa;text-transform:uppercase">Category</th>
        <th style="padding:8px 12px;text-align:center;font-size:12px;color:#aaa;text-transform:uppercase">Score</th>
        <th style="padding:8px 12px;text-align:center;font-size:12px;color:#aaa;text-transform:uppercase">Grade</th>
        <th style="padding:8px 12px;text-align:center;font-size:12px;color:#aaa;text-transform:uppercase">Severity</th>
      </tr>
    </thead>
    <tbody>
      ${catRows}
    </tbody>
  </table>

  <h2 style="font-size:18px;margin-bottom:12px">Detailed Findings</h2>
  ${detailSections}

  <div style="margin-top:40px;padding-top:16px;border-top:1px solid #222;text-align:center">
    <p style="font-size:12px;color:#555">Report generated by <a href="${branding.siteUrl}" target="_blank" rel="noopener noreferrer" style="color:#60a5fa">${branding.appName}</a> — ${timestamp()}</p>
  </div>

</div>
</body>
</html>`
}

// ── Public composable ─────────────────────────────────────────────────────

export function useReportExport() {
  const config = useRuntimeConfig()
  const branding: BrandingInfo = {
    appName: config.public.appName as string,
    siteUrl: config.public.siteUrl as string,
  }
  const exporting = ref(false)
  const sharing = ref(false)
  const shareUrl = ref<string | null>(null)
  const shareError = ref<string | null>(null)

  async function exportMarkdown(result: ReportResult) {
    const md = buildMarkdown(result, branding)
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' })
    saveAs(blob, `${baseFilename(result)}.md`)
  }

  async function exportJSON(result: ReportResult) {
    const json = buildJSON(result, branding)
    const blob = new Blob([json], { type: 'application/json;charset=utf-8' })
    saveAs(blob, `${baseFilename(result)}.json`)
  }

  async function exportDocx(result: ReportResult) {
    exporting.value = true
    try {
      const blob = await buildDocx(result, branding)
      saveAs(blob, `${baseFilename(result)}.docx`)
    } finally {
      exporting.value = false
    }
  }

  async function exportHtml(result: ReportResult) {
    const html = buildHtml(result, branding)
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
    saveAs(blob, `${baseFilename(result)}.html`)
  }

  async function shareReport(result: ReportResult): Promise<string | null> {
    sharing.value = true
    shareError.value = null
    shareUrl.value = null
    try {
      const response = await $fetch<{ id: string }>('/api/reports', {
        method: 'POST',
        body: { report: result },
        credentials: 'include',
      })
      const config = useRuntimeConfig()
      const url = `${config.public.siteUrl}/report/${response.id}`
      shareUrl.value = url
      return url
    } catch (err: any) {
      shareError.value = err?.data?.error || 'Failed to create share link'
      return null
    } finally {
      sharing.value = false
    }
  }

  function clearShare() {
    shareUrl.value = null
    shareError.value = null
  }

  return {
    exportMarkdown, exportJSON, exportDocx, exportHtml,
    shareReport, shareUrl, shareError, sharing, clearShare,
    exporting,
  }
}
