<template>
  <!-- 8. What is stored -->
  <section id="stored" class="scroll-mt-8">
    <h2 class="text-2xl font-bold text-[var(--text-heading)] mb-3">8. What is and isn't stored</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <div class="rounded-xl border border-emerald-700/40 bg-emerald-950/15 p-5">
        <h3 class="text-sm font-semibold uppercase tracking-wider text-emerald-300 mb-3">
          Stored (metadata only)
        </h3>
        <ul class="space-y-1.5 text-xs text-[var(--text-secondary)] list-disc list-inside">
          <li>Filename of the uploaded file (sanitized before storage)</li>
          <li>
            For a refused upload (a file type the tool cannot check): the file name it was offered
            under (sanitized) and a timestamp — the file itself is never accepted, so no content and
            no content hash exist
          </li>
          <li>SHA-256 hash of file bytes (a 64-character hex digest)</li>
          <li>Page count (integer)</li>
          <li>Pre-flight audit score and grade (numbers + letter)</li>
          <li>Post-remediation audit score and grade</li>
          <li>
            Per-category findings and explanations (generated by the scorer; in a
            <em>saved or shared</em> report these can quote short strings from the document — see §
            8a)
          </li>
          <li>
            For a shared report or remediation job only: document metadata (title, author, subject,
            keywords), image alt-text values, link text and destinations, bookmark titles, and
            form-field names, quoted inside the findings (§ 8a)
          </li>
          <li>User's email address (only if logged in; tied to the user's own account)</li>
          <li>
            Caller IP address and browser user-agent string (usage log; purged with the same 365-day
            retention)
          </li>
          <li>Server-side timestamps for every lifecycle event</li>
          <li>Job status, step name, progress percentage</li>
          <li>Failure reasons (string descriptions, no content)</li>
          <li>veraPDF verdict summary (passed/failed + rule IDs of failing rules, no content)</li>
          <li>SHA-256 hash of download token (token itself never stored)</li>
          <li>SHA-256 hash of deleted file paths (paths never stored)</li>
        </ul>
      </div>
      <div class="rounded-xl border border-red-700/40 bg-red-950/15 p-5">
        <h3 class="text-sm font-semibold uppercase tracking-wider text-red-300 mb-3">
          Never stored
        </h3>
        <ul class="space-y-1.5 text-xs text-[var(--text-secondary)] list-disc list-inside">
          <li>
            File content of any audited format — PDF, Word, PowerPoint, or Excel (audit pipeline)
          </li>
          <li>
            PDF file content after a remediation completes (output is deleted on download or after
            30-minute TTL)
          </li>
          <li>
            Page or paragraph text from inside uploaded documents (a saved report quotes only the
            specific short strings listed opposite — § 8a)
          </li>
          <li>Images extracted from uploaded documents (none are stored)</li>
          <li>Form-field values from PDFs</li>
          <li>Any data transmitted to AI services (there are none — see § 4)</li>
          <li>Any data shared with third-party analytics, ad networks, or tracking services</li>
          <li>Browser fingerprints or cross-site tracking identifiers</li>
          <li>Raw file paths in lifecycle events (paths are hashed before storage)</li>
          <li>
            Raw download tokens (tokens are hashed; the original 32-byte random token is held in the
            URL only)
          </li>
          <li>
            Backups on any external or cloud service — nightly snapshots (tool v1.49.0+) exist only
            on the same server, in a directory outside the application, and only the 5 newest are
            kept (see § 7); nothing is copied off the machine by the application
          </li>
        </ul>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
// Static content extracted verbatim from pages/data-retention.vue
// (Phase F, task F2: section split) -- 8. What is and isn't stored. No reactive state;
// the page's own script setup (TOOL_VERSION etc.) is untouched and
// still lives in the page component per the version test's source scan.
</script>
