<template>
    <!-- 8. What is stored -->
    <section id="stored" class="scroll-mt-8">
      <h2 class="text-2xl font-bold text-[var(--text-heading)] mb-3">
        8. What is and isn't stored
      </h2>
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div class="rounded-xl border border-emerald-700/40 bg-emerald-950/15 p-5">
          <h3 class="text-sm font-semibold uppercase tracking-wider text-emerald-300 mb-3">
            Stored (metadata only)
          </h3>
          <ul class="space-y-1.5 text-xs text-[var(--text-secondary)] list-disc list-inside">
            <li>Filename of the uploaded file (sanitized before storage)</li>
            <li>SHA-256 hash of file bytes (a 64-character hex digest)</li>
            <li>Page count (integer)</li>
            <li>Pre-flight audit score and grade (numbers + letter)</li>
            <li>Post-remediation audit score and grade</li>
            <li>
              Per-category findings and explanations (text generated by the scorer, never copied
              from the file)
            </li>
            <li>User's email address (only if logged in; tied to the user's own account)</li>
            <li>Server-side timestamps for every lifecycle event</li>
            <li>Job status, step name, progress percentage</li>
            <li>Failure reasons (string descriptions, no content)</li>
            <li>veraPDF verdict summary (passed/failed + rule IDs of failing rules, no content)</li>
            <li>SHA-256 hash of download token (token itself never stored)</li>
            <li>SHA-256 hash of deleted file paths (paths never stored)</li>
          </ul>
        </div>
        <div class="rounded-xl border border-red-700/40 bg-red-950/15 p-5">
          <h3 class="text-sm font-semibold uppercase tracking-wider text-red-300 mb-3">
            Never stored
          </h3>
          <ul class="space-y-1.5 text-xs text-[var(--text-secondary)] list-disc list-inside">
            <li>
              File content of any audited format — PDF, Word, PowerPoint, or Excel (audit pipeline)
            </li>
            <li>
              PDF file content after a remediation completes (output is deleted on download or after
              30-minute TTL)
            </li>
            <li>Extracted text from inside uploaded documents</li>
            <li>Images extracted from uploaded documents (none are stored)</li>
            <li>Form-field values from PDFs</li>
            <li>Any data transmitted to AI services (there are none — see § 4)</li>
            <li>Any data shared with third-party analytics, ad networks, or tracking services</li>
            <li>Browser fingerprints or cross-site tracking identifiers</li>
            <li>IP addresses of users (beyond what's in standard web logs)</li>
            <li>Raw file paths in lifecycle events (paths are hashed before storage)</li>
            <li>
              Raw download tokens (tokens are hashed; the original 32-byte random token is held in
              the URL only)
            </li>
            <li>
              Backups of the SQLite database to external storage (the database is on the local
              filesystem only)
            </li>
          </ul>
        </div>
      </div>
    </section>
</template>

<script setup lang="ts">
// Static content extracted verbatim from pages/data-retention.vue
// (Phase F, task F2: section split) -- 8. What is and isn't stored. No reactive state;
// the page's own script setup (TOOL_VERSION etc.) is untouched and
// still lives in the page component per the version test's source scan.
</script>
