/**
 * Plain-text report builder — moved verbatim out of
 * composables/useReportExport.ts (Task F5). Pure function: no DOM, no Vue,
 * no side effects.
 *
 * Replaces the former Word/.docx export (which pulled in the ~0.5 MB `docx`
 * runtime for no real benefit over the existing Markdown/HTML/JSON formats).
 * Same content, zero dependencies.
 */
import { bannerMetaLine } from "~/utils/reportBanner";
import { naReason } from "~/utils/modeDivergence";
import {
  type ReportResult,
  type BrandingInfo,
  gradeLabel,
  getScoreProfiles,
  standardsBasis,
  conformanceHeading,
  timestamp,
} from "./shared";

export function buildText(result: ReportResult, branding: BrandingInfo): string {
  const RULE = "=".repeat(72);
  const SUB = "-".repeat(72);
  const out: string[] = [];
  const scoreProfiles = getScoreProfiles(result, branding.wcagVersion);

  out.push(result.filename);
  out.push(`Accessibility Report · ${bannerMetaLine(result.pageCount, result.fileType)}`);
  out.push(RULE);
  out.push(`Date:          ${timestamp()}`);
  out.push(`Overall score: ${result.overallScore}/100`);
  out.push(`Grade:         ${result.grade} — ${gradeLabel(result.grade)}`);
  if (result.isScanned) out.push("Status:        Scanned document detected");
  out.push("");

  if (result.conformance) {
    const cf = result.conformance;
    out.push(`WCAG ${branding.wcagVersion} CONFORMANCE`);
    out.push(SUB);
    out.push(conformanceHeading(cf, branding.wcagVersion));
    out.push("");
    out.push(cf.headline);
    out.push("");
    if (cf.failures.length) {
      out.push("Confirmed failures:");
      for (const f of cf.failures) {
        out.push(`  - ${f.sc} ${f.name} (Level ${f.level})`);
        out.push(`      ${f.issue}`);
        out.push(`      ${f.url}`);
      }
      out.push("");
    }
    if (cf.notAssessed.length) {
      out.push("Not evaluated automatically (manual review required):");
      for (const n of cf.notAssessed) out.push(`  - ${n.sc} ${n.name}`);
      out.push("");
    }
    out.push(standardsBasis(branding.wcagVersion));
    out.push("");
  }

  if (scoreProfiles.length > 1) {
    out.push("SCORE PROFILES");
    out.push(SUB);
    for (const pr of scoreProfiles) {
      out.push(`  ${pr.label}: ${pr.overallScore}/100 (${pr.grade})`);
      out.push(`      ${pr.description}`);
    }
    out.push("");
  }

  out.push("EXECUTIVE SUMMARY");
  out.push(SUB);
  out.push(result.executiveSummary);
  out.push("");

  if (result.warnings?.length) {
    out.push("Warnings:");
    for (const w of result.warnings) out.push(`  - ${w}`);
    out.push("");
  }

  out.push("CATEGORY SCORES");
  out.push(SUB);
  // Match the live/shared Score Table: scored categories, then a separate
  // "Not Included in Scoring" list ("Not assessed" vs "Not applicable").
  const txtScored = result.categories.filter((c) => c.score !== null);
  const txtNa = result.categories.filter((c) => c.score === null);
  for (const cat of txtScored) {
    const score = `${cat.score}/100`;
    const grade = cat.grade || "-";
    const sev = cat.severity || "N/A";
    out.push(`  ${cat.label.padEnd(26)} ${score.padStart(7)}  ${grade.padEnd(2)} ${sev}`);
  }
  out.push("");
  if (txtNa.length) {
    out.push("Not Included in Scoring:");
    for (const cat of txtNa) {
      const naLabel = cat.notAssessed ? "Not assessed" : "Not applicable";
      out.push(`  - ${cat.label} (${naLabel}): ${naReason(cat.id, cat.notAssessed)}`);
    }
    out.push("");
  }

  out.push("DETAILED FINDINGS");
  out.push(RULE);
  for (const cat of txtScored) {
    const scoreStr = `${cat.score}/100 (${cat.grade})`;
    out.push("");
    out.push(`${cat.label} — ${scoreStr}`);
    out.push(SUB);
    if (cat.severity) out.push(`Severity: ${cat.severity}`);
    if (cat.explanation) {
      out.push("");
      out.push(cat.explanation);
    }
    out.push("");
    out.push("Findings:");
    for (const f of cat.findings) out.push(`  - ${f}`);
    if (cat.helpLinks?.length) {
      out.push("");
      out.push("Resources:");
      for (const link of cat.helpLinks) out.push(`  - ${link.label}: ${link.url}`);
    }
    out.push("");
  }

  out.push(RULE);
  out.push(`Report generated by ${branding.appName} (${branding.siteUrl}) — ${timestamp()}`);

  return out.join("\n");
}
